### ISSUE TITLE
        waver.waverLevelCallback  出现循环引用，没法解决 请问是什么问题。orz

### ISSUE THREAD

**Issue by lhr000lhr** [kevinzhow/Waver#5]
__weak typeof(Waver) * weakWaver =waver;
        __block  double voiceSound = 0;
        __weak typeof(EaseMob) *easeMob = [EaseMob sharedInstance];
        waver.waverLevelCallback = ^() {
            
            //        [self.recorder updateMeters];
         
            voiceSound = [easeMob.deviceManager peekRecorderVoiceMeter];

            //            CGFloat normalizedValue = pow (10, voiceSound / 40);
            if (voiceSound>0.45) {
                voiceSound = 0.45;

            }

            weakWaver.level = voiceSound;
           NSLog(@"%lf",weakWaver.level);
        };

**Comment by kevinzhow** [comment]
参照下example
lhr000lhr <notifications@github.com>于2015年4月27日 周一上午11:40写道：

**Comment by lhr000lhr** [comment]
example  也有这个问题_(:з」∠)_

**Comment by kevinzhow** [comment]
嗯，waver 应该从 block 传进去，回头我更新下
lhr000lhr <notifications@github.com>于2015年4月27日 周一上午11:46写道：
